"""empty message

Revision ID: b6585621bac3
Revises: c805c0da58f4
Create Date: 2022-04-22 15:42:26.355498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6585621bac3'
down_revision = 'c805c0da58f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.VARCHAR(length=511), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
